// Core data type definitions for Investie app

export interface MarketSummaryData {
  fearGreedIndex: {
    value: number;
    status: 'fear' | 'neutral' | 'greed';
    color: string;
  };
  vix: {
    value: number;
    status: 'low' | 'medium' | 'high';
    color: string;
  };
  interestRate: {
    value: number;
    aiOutlook: string; // Generated by Claude
  };
  cpi: {
    value: number;
    monthOverMonth: number;
    direction: 'up' | 'down';
  };
  unemploymentRate: {
    value: number;
    monthOverMonth: number;
  };
  sp500Sparkline: number[];
}

export interface StockCardData {
  symbol: string;
  name: string;
  price: {
    current: number;
    change: number;
    changePercent: number;
  };
  pe: {
    value: number;
    industryAverage: number;
    evaluation: 'undervalued' | 'fair' | 'overvalued';
  };
  marketCap: number;
  volume: number;
  fiftyTwoWeek: {
    high: number;
    low: number;
  };
  rsi: {
    value: number;
    status: 'oversold' | 'neutral' | 'overbought';
  };
  newsSummary: string; // One-line summary from Claude
  sectorPerformance: {
    name: string;
    weeklyChange: number;
  };
}

export type StockSymbol = 'AAPL' | 'TSLA' | 'MSFT' | 'GOOGL' | 'AMZN' | 
                         'NVDA' | 'META' | 'NFLX' | 'AVGO' | 'AMD';

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  timestamp: string;
  source: string;
}